### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kiunye** [Sage/sageone_api_ruby_sample#17]
I keep getting an internal server error everytime I try to authorize the sage connection. All of my settings on the sageone.yml file are correct but sage can't authenticate

**Comment by timlapluie** [comment]
Hello @kchrismucheke,

could you please tell me the country of the Sage One product you are trying to connect to? Also, which API version do you use?

**Comment by kiunye** [comment]
I'm using version v3. The Sage product I'm trying to connect to is Sage One Core API - US

**Comment by timlapluie** [comment]
You need to use the `v3` branch of this repository. Enter all your credentials again in `sageone.yml` and be sure to use http://localhost:3000/auth/callback as callback URL (this also needs to be configured in your client application on https://developers.sageone.com/applications).

I just tested the connection to a US business and API v3 and this sample app directly works.

I hope I could help you with this. If you have further questions, don't hesitate to ask!

[EDIT]
We've just updated the `master` branch to use API v3 directly. Could you please retry the connection to Sage Business Cloud Accounting US and if it doesn't work, provide me detailed information/logs of the occurred error?

**Comment by kchrismucheke** [comment]
I'm still getting an error 403 in the terminal and internal server error on the browser

**Comment by kiunye** [comment]
Thank you it's worked finally

**Comment by timlapluie** [comment]
Nice to hear that! 😄

**Comment by AnujShah114** [comment]
Hey! I am trying to authenticate my sage accounting application(canada) but every time I try in postman it shoots 404 error "It doesn't exist... Sorry, we can't find the page that you are looking for. This could be due to a misspelled URL or an out of date bookmark."

Below is my access token request.
Callback URL: https://getpostman.com/oauth2/callback
Auth URL: https://www.sageone.com/oauth2/auth/central?filter=apiv3.1
Access Token URL: http://app.sageone.com/oauth2/token
Client ID: XXXX5536...........
Client Secrest: adaa6834a........
Scope: full_access
state: random_string

**Comment by timlapluie** [comment]
@AnujShah114 
You are using the wrong token URL. Please change it to 
* https://oauth.accounting.sage.com/token for API v3.1
* https://oauth.na.sageone.com/token for API v3

It is important to know that you cannot use the v3 URL for v3.1 and vice versa.
